package org.test;

import java.awt.Dimension;
import java.io.File;
import javax.swing.ImageIcon;

public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        this.setPreferredSize(new Dimension(1024,768));
        initComponents();
        initComponents2();
        testLoadCard();
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jpPlayersOvest = new javax.swing.JPanel();
        jpPlayer1 = new javax.swing.JPanel();
        jlP1Name = new javax.swing.JLabel();
        jlP1Card1 = new javax.swing.JLabel();
        jlP1Card2 = new javax.swing.JLabel();
        jlP1Card3 = new javax.swing.JLabel();
        jlP1Card4 = new javax.swing.JLabel();
        jlP1Card5 = new javax.swing.JLabel();
        jlP1Card6 = new javax.swing.JLabel();
        jlP1Card7 = new javax.swing.JLabel();
        jlP1Card8 = new javax.swing.JLabel();
        jlP1Card9 = new javax.swing.JLabel();
        jlP1Card10 = new javax.swing.JLabel();
        jlP1Card11 = new javax.swing.JLabel();
        jlP1Card12 = new javax.swing.JLabel();
        jpPlayer2 = new javax.swing.JPanel();
        jlP2Name = new javax.swing.JLabel();
        jlP2Card1 = new javax.swing.JLabel();
        jlP2Card2 = new javax.swing.JLabel();
        jlP2Card3 = new javax.swing.JLabel();
        jlP2Card4 = new javax.swing.JLabel();
        jlP2Card5 = new javax.swing.JLabel();
        jlP2Card6 = new javax.swing.JLabel();
        jlP2Card7 = new javax.swing.JLabel();
        jlP2Card8 = new javax.swing.JLabel();
        jlP2Card9 = new javax.swing.JLabel();
        jlP2Card10 = new javax.swing.JLabel();
        jlP2Card11 = new javax.swing.JLabel();
        jlP2Card12 = new javax.swing.JLabel();
        jpPlayer3 = new javax.swing.JPanel();
        jlP3Name = new javax.swing.JLabel();
        jlP3Card1 = new javax.swing.JLabel();
        jlP3Card2 = new javax.swing.JLabel();
        jlP3Card3 = new javax.swing.JLabel();
        jlP3Card4 = new javax.swing.JLabel();
        jlP3Card5 = new javax.swing.JLabel();
        jlP3Card6 = new javax.swing.JLabel();
        jlP3Card7 = new javax.swing.JLabel();
        jlP3Card8 = new javax.swing.JLabel();
        jlP3Card9 = new javax.swing.JLabel();
        jlP3Card10 = new javax.swing.JLabel();
        jlP3Card11 = new javax.swing.JLabel();
        jlP3Card12 = new javax.swing.JLabel();
        jpPlayer4 = new javax.swing.JPanel();
        jlP4Name = new javax.swing.JLabel();
        jlP4Card1 = new javax.swing.JLabel();
        jlP4Card2 = new javax.swing.JLabel();
        jlP4Card3 = new javax.swing.JLabel();
        jlP4Card4 = new javax.swing.JLabel();
        jlP4Card5 = new javax.swing.JLabel();
        jlP4Card6 = new javax.swing.JLabel();
        jlP4Card7 = new javax.swing.JLabel();
        jlP4Card8 = new javax.swing.JLabel();
        jlP4Card9 = new javax.swing.JLabel();
        jlP4Card10 = new javax.swing.JLabel();
        jlP4Card11 = new javax.swing.JLabel();
        jlP4Card12 = new javax.swing.JLabel();
        jpPlayer5 = new javax.swing.JPanel();
        jlP5Name = new javax.swing.JLabel();
        jlP5Card1 = new javax.swing.JLabel();
        jlP5Card2 = new javax.swing.JLabel();
        jlP5Card3 = new javax.swing.JLabel();
        jlP5Card4 = new javax.swing.JLabel();
        jlP5Card5 = new javax.swing.JLabel();
        jlP5Card6 = new javax.swing.JLabel();
        jlP5Card7 = new javax.swing.JLabel();
        jlP5Card8 = new javax.swing.JLabel();
        jlP5Card9 = new javax.swing.JLabel();
        jlP5Card10 = new javax.swing.JLabel();
        jlP5Card11 = new javax.swing.JLabel();
        jlP5Card12 = new javax.swing.JLabel();
        jpPlayer6 = new javax.swing.JPanel();
        jlP6Name = new javax.swing.JLabel();
        jlP6Card1 = new javax.swing.JLabel();
        jlP6Card2 = new javax.swing.JLabel();
        jlP6Card3 = new javax.swing.JLabel();
        jlP6Card4 = new javax.swing.JLabel();
        jlP6Card5 = new javax.swing.JLabel();
        jlP6Card6 = new javax.swing.JLabel();
        jlP6Card7 = new javax.swing.JLabel();
        jlP6Card8 = new javax.swing.JLabel();
        jlP6Card9 = new javax.swing.JLabel();
        jlP6Card10 = new javax.swing.JLabel();
        jlP6Card11 = new javax.swing.JLabel();
        jlP6Card12 = new javax.swing.JLabel();
        jpPlayersEast = new javax.swing.JPanel();
        jpPlayer7 = new javax.swing.JPanel();
        jlP7Name = new javax.swing.JLabel();
        jlP7Card1 = new javax.swing.JLabel();
        jlP7Card2 = new javax.swing.JLabel();
        jlP7Card3 = new javax.swing.JLabel();
        jlP7Card4 = new javax.swing.JLabel();
        jlP7Card5 = new javax.swing.JLabel();
        jlP7Card6 = new javax.swing.JLabel();
        jlP7Card7 = new javax.swing.JLabel();
        jlP7Card8 = new javax.swing.JLabel();
        jlP7Card9 = new javax.swing.JLabel();
        jlP7Card10 = new javax.swing.JLabel();
        jlP7Card11 = new javax.swing.JLabel();
        jlP7Card12 = new javax.swing.JLabel();
        jpPlayer8 = new javax.swing.JPanel();
        jlP8Name = new javax.swing.JLabel();
        jlP8Card1 = new javax.swing.JLabel();
        jlP8Card2 = new javax.swing.JLabel();
        jlP8Card3 = new javax.swing.JLabel();
        jlP8Card4 = new javax.swing.JLabel();
        jlP8Card5 = new javax.swing.JLabel();
        jlP8Card6 = new javax.swing.JLabel();
        jlP8Card7 = new javax.swing.JLabel();
        jlP8Card8 = new javax.swing.JLabel();
        jlP8Card9 = new javax.swing.JLabel();
        jlP8Card10 = new javax.swing.JLabel();
        jlP8Card11 = new javax.swing.JLabel();
        jlP8Card12 = new javax.swing.JLabel();
        jpPlayer9 = new javax.swing.JPanel();
        jlP9Name = new javax.swing.JLabel();
        jlP9Card1 = new javax.swing.JLabel();
        jlP9Card2 = new javax.swing.JLabel();
        jlP9Card3 = new javax.swing.JLabel();
        jlP9Card4 = new javax.swing.JLabel();
        jlP9Card5 = new javax.swing.JLabel();
        jlP9Card6 = new javax.swing.JLabel();
        jlP9Card7 = new javax.swing.JLabel();
        jlP9Card8 = new javax.swing.JLabel();
        jlP9Card9 = new javax.swing.JLabel();
        jlP9Card10 = new javax.swing.JLabel();
        jlP9Card11 = new javax.swing.JLabel();
        jlP9Card12 = new javax.swing.JLabel();
        jpPlayer10 = new javax.swing.JPanel();
        jlP10Name = new javax.swing.JLabel();
        jlP10Card1 = new javax.swing.JLabel();
        jlP10Card2 = new javax.swing.JLabel();
        jlP10Card3 = new javax.swing.JLabel();
        jlP10Card4 = new javax.swing.JLabel();
        jlP10Card5 = new javax.swing.JLabel();
        jlP10Card6 = new javax.swing.JLabel();
        jlP10Card7 = new javax.swing.JLabel();
        jlP10Card8 = new javax.swing.JLabel();
        jlP10Card9 = new javax.swing.JLabel();
        jlP10Card10 = new javax.swing.JLabel();
        jlP10Card11 = new javax.swing.JLabel();
        jlP10Card12 = new javax.swing.JLabel();
        jpPlayer11 = new javax.swing.JPanel();
        jlP11Name = new javax.swing.JLabel();
        jlP11Card1 = new javax.swing.JLabel();
        jlP11Card2 = new javax.swing.JLabel();
        jlP11Card3 = new javax.swing.JLabel();
        jlP11Card4 = new javax.swing.JLabel();
        jlP11Card5 = new javax.swing.JLabel();
        jlP11Card6 = new javax.swing.JLabel();
        jlP11Card7 = new javax.swing.JLabel();
        jlP11Card8 = new javax.swing.JLabel();
        jlP11Card9 = new javax.swing.JLabel();
        jlP11Card10 = new javax.swing.JLabel();
        jlP11Card11 = new javax.swing.JLabel();
        jlP11Card12 = new javax.swing.JLabel();
        jpPlayer0 = new javax.swing.JPanel();
        jlP0Name = new javax.swing.JLabel();
        jlP0Card1 = new javax.swing.JLabel();
        jlP0Card2 = new javax.swing.JLabel();
        jlP0Card3 = new javax.swing.JLabel();
        jlP0Card4 = new javax.swing.JLabel();
        jlP0Card5 = new javax.swing.JLabel();
        jlP0Card6 = new javax.swing.JLabel();
        jlP0Card7 = new javax.swing.JLabel();
        jlP0Card8 = new javax.swing.JLabel();
        jlP0Card9 = new javax.swing.JLabel();
        jlP0Card10 = new javax.swing.JLabel();
        jlP0Card11 = new javax.swing.JLabel();
        jlP0Card12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jlP1Name.setText("giocatore1");

        jlP1Card1.setText("jl1");

        jlP1Card2.setText("jl2");

        jlP1Card3.setText("jl3");

        jlP1Card4.setText("jl4");

        jlP1Card5.setText("jl5");

        jlP1Card6.setText("jl6");

        jlP1Card7.setText("jl7");

        jlP1Card8.setText("jl8");

        jlP1Card9.setText("jl9");

        jlP1Card10.setText("jl10");

        jlP1Card11.setText("jl11");

        jlP1Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer1Layout = new javax.swing.GroupLayout(jpPlayer1);
        jpPlayer1.setLayout(jpPlayer1Layout);
        jpPlayer1Layout.setHorizontalGroup(
            jpPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer1Layout.createSequentialGroup()
                .addComponent(jlP1Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlP1Card1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP1Card2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP1Card3)
                .addGap(6, 6, 6)
                .addComponent(jlP1Card4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP1Card5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP1Card6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP1Card7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP1Card8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP1Card9)
                .addGap(6, 6, 6)
                .addComponent(jlP1Card10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP1Card11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP1Card12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPlayer1Layout.setVerticalGroup(
            jpPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer1Layout.createSequentialGroup()
                .addGroup(jpPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP1Name)
                    .addComponent(jlP1Card1)
                    .addComponent(jlP1Card2)
                    .addComponent(jlP1Card3)
                    .addComponent(jlP1Card4)
                    .addComponent(jlP1Card5)
                    .addComponent(jlP1Card6)
                    .addComponent(jlP1Card7)
                    .addComponent(jlP1Card8)
                    .addComponent(jlP1Card9)
                    .addComponent(jlP1Card10)
                    .addComponent(jlP1Card11)
                    .addComponent(jlP1Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP2Name.setText("giocatore2");

        jlP2Card1.setText("jl1");

        jlP2Card2.setText("jl2");

        jlP2Card3.setText("jl3");

        jlP2Card4.setText("jl4");

        jlP2Card5.setText("jl5");

        jlP2Card6.setText("jl6");

        jlP2Card7.setText("jl7");

        jlP2Card8.setText("jl8");

        jlP2Card9.setText("jl9");

        jlP2Card10.setText("jl10");

        jlP2Card11.setText("jl11");

        jlP2Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer2Layout = new javax.swing.GroupLayout(jpPlayer2);
        jpPlayer2.setLayout(jpPlayer2Layout);
        jpPlayer2Layout.setHorizontalGroup(
            jpPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer2Layout.createSequentialGroup()
                .addGroup(jpPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlP2Name)
                    .addGroup(jpPlayer2Layout.createSequentialGroup()
                        .addComponent(jlP2Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP2Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP2Card3)
                        .addGap(6, 6, 6)
                        .addComponent(jlP2Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP2Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP2Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP2Card7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP2Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP2Card9)
                        .addGap(6, 6, 6)
                        .addComponent(jlP2Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP2Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP2Card12)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jpPlayer2Layout.setVerticalGroup(
            jpPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer2Layout.createSequentialGroup()
                .addComponent(jlP2Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP2Card1)
                    .addComponent(jlP2Card2)
                    .addComponent(jlP2Card3)
                    .addComponent(jlP2Card4)
                    .addComponent(jlP2Card5)
                    .addComponent(jlP2Card6)
                    .addComponent(jlP2Card7)
                    .addComponent(jlP2Card8)
                    .addComponent(jlP2Card9)
                    .addComponent(jlP2Card10)
                    .addComponent(jlP2Card11)
                    .addComponent(jlP2Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP3Name.setText("giocatore3");

        jlP3Card1.setText("jl1");

        jlP3Card2.setText("jl2");

        jlP3Card3.setText("jl3");

        jlP3Card4.setText("jl4");

        jlP3Card5.setText("jl5");

        jlP3Card6.setText("jl6");

        jlP3Card7.setText("jl7");

        jlP3Card8.setText("jl8");

        jlP3Card9.setText("jl9");

        jlP3Card10.setText("jl10");

        jlP3Card11.setText("jl11");

        jlP3Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer3Layout = new javax.swing.GroupLayout(jpPlayer3);
        jpPlayer3.setLayout(jpPlayer3Layout);
        jpPlayer3Layout.setHorizontalGroup(
            jpPlayer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer3Layout.createSequentialGroup()
                .addGroup(jpPlayer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlP3Name)
                    .addGroup(jpPlayer3Layout.createSequentialGroup()
                        .addComponent(jlP3Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP3Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP3Card3)
                        .addGap(6, 6, 6)
                        .addComponent(jlP3Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP3Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP3Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP3Card7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP3Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP3Card9)
                        .addGap(6, 6, 6)
                        .addComponent(jlP3Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP3Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP3Card12)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jpPlayer3Layout.setVerticalGroup(
            jpPlayer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer3Layout.createSequentialGroup()
                .addComponent(jlP3Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP3Card1)
                    .addComponent(jlP3Card2)
                    .addComponent(jlP3Card3)
                    .addComponent(jlP3Card4)
                    .addComponent(jlP3Card5)
                    .addComponent(jlP3Card6)
                    .addComponent(jlP3Card7)
                    .addComponent(jlP3Card8)
                    .addComponent(jlP3Card9)
                    .addComponent(jlP3Card10)
                    .addComponent(jlP3Card11)
                    .addComponent(jlP3Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP4Name.setText("giocatore4");

        jlP4Card1.setText("jl1");

        jlP4Card2.setText("jl2");

        jlP4Card3.setText("jl3");

        jlP4Card4.setText("jl4");

        jlP4Card5.setText("jl5");

        jlP4Card6.setText("jl6");

        jlP4Card7.setText("jl7");

        jlP4Card8.setText("jl8");

        jlP4Card9.setText("jl9");

        jlP4Card10.setText("jl10");

        jlP4Card11.setText("jl11");

        jlP4Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer4Layout = new javax.swing.GroupLayout(jpPlayer4);
        jpPlayer4.setLayout(jpPlayer4Layout);
        jpPlayer4Layout.setHorizontalGroup(
            jpPlayer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer4Layout.createSequentialGroup()
                .addGroup(jpPlayer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlP4Name)
                    .addGroup(jpPlayer4Layout.createSequentialGroup()
                        .addComponent(jlP4Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP4Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP4Card3)
                        .addGap(6, 6, 6)
                        .addComponent(jlP4Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP4Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP4Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlP4Card7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP4Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP4Card9)
                        .addGap(6, 6, 6)
                        .addComponent(jlP4Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP4Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP4Card12)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jpPlayer4Layout.setVerticalGroup(
            jpPlayer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer4Layout.createSequentialGroup()
                .addComponent(jlP4Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP4Card1)
                    .addComponent(jlP4Card2)
                    .addComponent(jlP4Card3)
                    .addComponent(jlP4Card4)
                    .addComponent(jlP4Card5)
                    .addComponent(jlP4Card6)
                    .addComponent(jlP4Card7)
                    .addComponent(jlP4Card8)
                    .addComponent(jlP4Card9)
                    .addComponent(jlP4Card10)
                    .addComponent(jlP4Card11)
                    .addComponent(jlP4Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP5Name.setText("giocatore5");

        jlP5Card1.setText("jl1");

        jlP5Card2.setText("jl2");

        jlP5Card3.setText("jl3");

        jlP5Card4.setText("jl4");

        jlP5Card5.setText("jl5");

        jlP5Card6.setText("jl6");

        jlP5Card7.setText("jl7");

        jlP5Card8.setText("jl8");

        jlP5Card9.setText("jl9");

        jlP5Card10.setText("jl10");

        jlP5Card11.setText("jl11");

        jlP5Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer5Layout = new javax.swing.GroupLayout(jpPlayer5);
        jpPlayer5.setLayout(jpPlayer5Layout);
        jpPlayer5Layout.setHorizontalGroup(
            jpPlayer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer5Layout.createSequentialGroup()
                .addGroup(jpPlayer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlP5Name)
                    .addGroup(jpPlayer5Layout.createSequentialGroup()
                        .addComponent(jlP5Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP5Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP5Card3)
                        .addGap(6, 6, 6)
                        .addComponent(jlP5Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP5Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP5Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP5Card7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP5Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP5Card9)
                        .addGap(6, 6, 6)
                        .addComponent(jlP5Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP5Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP5Card12)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jpPlayer5Layout.setVerticalGroup(
            jpPlayer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer5Layout.createSequentialGroup()
                .addComponent(jlP5Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP5Card1)
                    .addComponent(jlP5Card2)
                    .addComponent(jlP5Card3)
                    .addComponent(jlP5Card4)
                    .addComponent(jlP5Card5)
                    .addComponent(jlP5Card6)
                    .addComponent(jlP5Card7)
                    .addComponent(jlP5Card8)
                    .addComponent(jlP5Card9)
                    .addComponent(jlP5Card10)
                    .addComponent(jlP5Card11)
                    .addComponent(jlP5Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP6Name.setText("giocatore6");

        jlP6Card1.setText("jl1");

        jlP6Card2.setText("jl2");

        jlP6Card3.setText("jl3");

        jlP6Card4.setText("jl4");

        jlP6Card5.setText("jl5");

        jlP6Card6.setText("jl6");

        jlP6Card7.setText("jl7");

        jlP6Card8.setText("jl8");

        jlP6Card9.setText("jl9");

        jlP6Card10.setText("jl10");

        jlP6Card11.setText("jl11");

        jlP6Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer6Layout = new javax.swing.GroupLayout(jpPlayer6);
        jpPlayer6.setLayout(jpPlayer6Layout);
        jpPlayer6Layout.setHorizontalGroup(
            jpPlayer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer6Layout.createSequentialGroup()
                .addGroup(jpPlayer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlP6Name)
                    .addGroup(jpPlayer6Layout.createSequentialGroup()
                        .addComponent(jlP6Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP6Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP6Card3)
                        .addGap(6, 6, 6)
                        .addComponent(jlP6Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP6Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP6Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP6Card7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP6Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP6Card9)
                        .addGap(6, 6, 6)
                        .addComponent(jlP6Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP6Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP6Card12)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jpPlayer6Layout.setVerticalGroup(
            jpPlayer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer6Layout.createSequentialGroup()
                .addComponent(jlP6Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP6Card1)
                    .addComponent(jlP6Card2)
                    .addComponent(jlP6Card3)
                    .addComponent(jlP6Card4)
                    .addComponent(jlP6Card5)
                    .addComponent(jlP6Card6)
                    .addComponent(jlP6Card7)
                    .addComponent(jlP6Card8)
                    .addComponent(jlP6Card9)
                    .addComponent(jlP6Card10)
                    .addComponent(jlP6Card11)
                    .addComponent(jlP6Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPlayersOvestLayout = new javax.swing.GroupLayout(jpPlayersOvest);
        jpPlayersOvest.setLayout(jpPlayersOvestLayout);
        jpPlayersOvestLayout.setHorizontalGroup(
            jpPlayersOvestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayersOvestLayout.createSequentialGroup()
                .addGroup(jpPlayersOvestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpPlayer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPlayer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPlayer5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jpPlayersOvestLayout.setVerticalGroup(
            jpPlayersOvestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayersOvestLayout.createSequentialGroup()
                .addComponent(jpPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jlP7Name.setText("giocatore7");

        jlP7Card1.setText("jl1");

        jlP7Card2.setText("jl2");

        jlP7Card3.setText("jl3");

        jlP7Card4.setText("jl4");

        jlP7Card5.setText("jl5");

        jlP7Card6.setText("jl6");

        jlP7Card7.setText("jl7");

        jlP7Card8.setText("jl8");

        jlP7Card9.setText("jl9");

        jlP7Card10.setText("jl10");

        jlP7Card11.setText("jl11");

        jlP7Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer7Layout = new javax.swing.GroupLayout(jpPlayer7);
        jpPlayer7.setLayout(jpPlayer7Layout);
        jpPlayer7Layout.setHorizontalGroup(
            jpPlayer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlP7Card12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP7Card11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP7Card10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP7Card9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP7Card8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlP7Card7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer7Layout.createSequentialGroup()
                        .addComponent(jlP7Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP7Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP7Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP7Card3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP7Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP7Card1))
                    .addComponent(jlP7Name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jpPlayer7Layout.setVerticalGroup(
            jpPlayer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer7Layout.createSequentialGroup()
                .addComponent(jlP7Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP7Card1)
                    .addComponent(jlP7Card2)
                    .addComponent(jlP7Card3)
                    .addComponent(jlP7Card4)
                    .addComponent(jlP7Card5)
                    .addComponent(jlP7Card6)
                    .addComponent(jlP7Card7)
                    .addComponent(jlP7Card8)
                    .addComponent(jlP7Card9)
                    .addComponent(jlP7Card10)
                    .addComponent(jlP7Card11)
                    .addComponent(jlP7Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP8Name.setText("giocatore8");

        jlP8Card1.setText("jl1");

        jlP8Card2.setText("jl2");

        jlP8Card3.setText("jl3");

        jlP8Card4.setText("jl4");

        jlP8Card5.setText("jl5");

        jlP8Card6.setText("jl6");

        jlP8Card7.setText("jl7");

        jlP8Card8.setText("jl8");

        jlP8Card9.setText("jl9");

        jlP8Card10.setText("jl10");

        jlP8Card11.setText("jl11");

        jlP8Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer8Layout = new javax.swing.GroupLayout(jpPlayer8);
        jpPlayer8.setLayout(jpPlayer8Layout);
        jpPlayer8Layout.setHorizontalGroup(
            jpPlayer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer8Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jpPlayer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer8Layout.createSequentialGroup()
                        .addComponent(jlP8Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer8Layout.createSequentialGroup()
                        .addComponent(jlP8Card12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP8Card7))
                    .addComponent(jlP8Name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jpPlayer8Layout.setVerticalGroup(
            jpPlayer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer8Layout.createSequentialGroup()
                .addComponent(jlP8Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP8Card1)
                    .addComponent(jlP8Card2)
                    .addComponent(jlP8Card3)
                    .addComponent(jlP8Card4)
                    .addComponent(jlP8Card5)
                    .addComponent(jlP8Card6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPlayer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP8Card7)
                    .addComponent(jlP8Card8)
                    .addComponent(jlP8Card9)
                    .addComponent(jlP8Card10)
                    .addComponent(jlP8Card11)
                    .addComponent(jlP8Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP9Name.setText("giocatore9");

        jlP9Card1.setText("jl1");

        jlP9Card2.setText("jl2");

        jlP9Card3.setText("jl3");

        jlP9Card4.setText("jl4");

        jlP9Card5.setText("jl5");

        jlP9Card6.setText("jl6");

        jlP9Card7.setText("jl7");

        jlP9Card8.setText("jl8");

        jlP9Card9.setText("jl9");

        jlP9Card10.setText("jl10");

        jlP9Card11.setText("jl11");

        jlP9Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer9Layout = new javax.swing.GroupLayout(jpPlayer9);
        jpPlayer9.setLayout(jpPlayer9Layout);
        jpPlayer9Layout.setHorizontalGroup(
            jpPlayer9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer9Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jpPlayer9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer9Layout.createSequentialGroup()
                        .addComponent(jlP9Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer9Layout.createSequentialGroup()
                        .addComponent(jlP9Card12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP9Card7))
                    .addComponent(jlP9Name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jpPlayer9Layout.setVerticalGroup(
            jpPlayer9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer9Layout.createSequentialGroup()
                .addComponent(jlP9Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP9Card1)
                    .addComponent(jlP9Card2)
                    .addComponent(jlP9Card3)
                    .addComponent(jlP9Card4)
                    .addComponent(jlP9Card5)
                    .addComponent(jlP9Card6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPlayer9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP9Card7)
                    .addComponent(jlP9Card8)
                    .addComponent(jlP9Card9)
                    .addComponent(jlP9Card10)
                    .addComponent(jlP9Card11)
                    .addComponent(jlP9Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP10Name.setText("giocatore10");

        jlP10Card1.setText("jl1");

        jlP10Card2.setText("jl2");

        jlP10Card3.setText("jl3");

        jlP10Card4.setText("jl4");

        jlP10Card5.setText("jl5");

        jlP10Card6.setText("jl6");

        jlP10Card7.setText("jl7");

        jlP10Card8.setText("jl8");

        jlP10Card9.setText("jl9");

        jlP10Card10.setText("jl10");

        jlP10Card11.setText("jl11");

        jlP10Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer10Layout = new javax.swing.GroupLayout(jpPlayer10);
        jpPlayer10.setLayout(jpPlayer10Layout);
        jpPlayer10Layout.setHorizontalGroup(
            jpPlayer10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer10Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jpPlayer10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer10Layout.createSequentialGroup()
                        .addComponent(jlP10Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer10Layout.createSequentialGroup()
                        .addComponent(jlP10Card12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP10Card7))
                    .addComponent(jlP10Name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jpPlayer10Layout.setVerticalGroup(
            jpPlayer10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer10Layout.createSequentialGroup()
                .addComponent(jlP10Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP10Card1)
                    .addComponent(jlP10Card2)
                    .addComponent(jlP10Card3)
                    .addComponent(jlP10Card4)
                    .addComponent(jlP10Card5)
                    .addComponent(jlP10Card6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPlayer10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP10Card7)
                    .addComponent(jlP10Card8)
                    .addComponent(jlP10Card9)
                    .addComponent(jlP10Card10)
                    .addComponent(jlP10Card11)
                    .addComponent(jlP10Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP11Name.setText("giocatore11");

        jlP11Card1.setText("jl1");

        jlP11Card2.setText("jl2");

        jlP11Card3.setText("jl3");

        jlP11Card4.setText("jl4");

        jlP11Card5.setText("jl5");

        jlP11Card6.setText("jl6");

        jlP11Card7.setText("jl7");

        jlP11Card8.setText("jl8");

        jlP11Card9.setText("jl9");

        jlP11Card10.setText("jl10");

        jlP11Card11.setText("jl11");

        jlP11Card12.setText("jl12");

        javax.swing.GroupLayout jpPlayer11Layout = new javax.swing.GroupLayout(jpPlayer11);
        jpPlayer11.setLayout(jpPlayer11Layout);
        jpPlayer11Layout.setHorizontalGroup(
            jpPlayer11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer11Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jpPlayer11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer11Layout.createSequentialGroup()
                        .addComponent(jlP11Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer11Layout.createSequentialGroup()
                        .addComponent(jlP11Card12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP11Card7))
                    .addComponent(jlP11Name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jpPlayer11Layout.setVerticalGroup(
            jpPlayer11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer11Layout.createSequentialGroup()
                .addComponent(jlP11Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP11Card1)
                    .addComponent(jlP11Card2)
                    .addComponent(jlP11Card3)
                    .addComponent(jlP11Card4)
                    .addComponent(jlP11Card5)
                    .addComponent(jlP11Card6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPlayer11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP11Card7)
                    .addComponent(jlP11Card8)
                    .addComponent(jlP11Card9)
                    .addComponent(jlP11Card10)
                    .addComponent(jlP11Card11)
                    .addComponent(jlP11Card12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPlayersEastLayout = new javax.swing.GroupLayout(jpPlayersEast);
        jpPlayersEast.setLayout(jpPlayersEastLayout);
        jpPlayersEastLayout.setHorizontalGroup(
            jpPlayersEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayersEastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPlayersEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpPlayer7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPlayer8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPlayer9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPlayer10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPlayer11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPlayersEastLayout.setVerticalGroup(
            jpPlayersEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayersEastLayout.createSequentialGroup()
                .addComponent(jpPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jpPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlP0Name.setText("giocatore0");

        jlP0Card1.setText("jl1");

        jlP0Card2.setText("jl2");

        jlP0Card3.setText("jl3");

        jlP0Card4.setText("jl4");

        jlP0Card5.setText("jl5");

        jlP0Card6.setText("jl6");

        jlP0Card7.setText("jl7");

        jlP0Card8.setText("jl8");

        jlP0Card9.setText("jl9");

        jlP0Card10.setText("jl10");

        jlP0Card11.setText("jl11");

        jlP0Card12.setText("jl12");

        jLabel1.setText("Mazziere");

        javax.swing.GroupLayout jpPlayer0Layout = new javax.swing.GroupLayout(jpPlayer0);
        jpPlayer0.setLayout(jpPlayer0Layout);
        jpPlayer0Layout.setHorizontalGroup(
            jpPlayer0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayer0Layout.createSequentialGroup()
                .addGroup(jpPlayer0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPlayer0Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Name))
                    .addGroup(jpPlayer0Layout.createSequentialGroup()
                        .addComponent(jlP0Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlP0Card12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPlayer0Layout.setVerticalGroup(
            jpPlayer0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayer0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPlayer0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP0Card1)
                    .addComponent(jlP0Card2)
                    .addComponent(jlP0Card3)
                    .addComponent(jlP0Card4)
                    .addComponent(jlP0Card5)
                    .addComponent(jlP0Card6)
                    .addComponent(jlP0Card7)
                    .addComponent(jlP0Card8)
                    .addComponent(jlP0Card9)
                    .addComponent(jlP0Card10)
                    .addComponent(jlP0Card11)
                    .addComponent(jlP0Card12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlayer0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlP0Name)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpPlayersOvest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpPlayersEast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(jpPlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpPlayersOvest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jpPlayer0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPlayersEast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void initComponents2() {

    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlP0Card1;
    private javax.swing.JLabel jlP0Card10;
    private javax.swing.JLabel jlP0Card11;
    private javax.swing.JLabel jlP0Card12;
    private javax.swing.JLabel jlP0Card2;
    private javax.swing.JLabel jlP0Card3;
    private javax.swing.JLabel jlP0Card4;
    private javax.swing.JLabel jlP0Card5;
    private javax.swing.JLabel jlP0Card6;
    private javax.swing.JLabel jlP0Card7;
    private javax.swing.JLabel jlP0Card8;
    private javax.swing.JLabel jlP0Card9;
    private javax.swing.JLabel jlP0Name;
    private javax.swing.JLabel jlP10Card1;
    private javax.swing.JLabel jlP10Card10;
    private javax.swing.JLabel jlP10Card11;
    private javax.swing.JLabel jlP10Card12;
    private javax.swing.JLabel jlP10Card2;
    private javax.swing.JLabel jlP10Card3;
    private javax.swing.JLabel jlP10Card4;
    private javax.swing.JLabel jlP10Card5;
    private javax.swing.JLabel jlP10Card6;
    private javax.swing.JLabel jlP10Card7;
    private javax.swing.JLabel jlP10Card8;
    private javax.swing.JLabel jlP10Card9;
    private javax.swing.JLabel jlP10Name;
    private javax.swing.JLabel jlP11Card1;
    private javax.swing.JLabel jlP11Card10;
    private javax.swing.JLabel jlP11Card11;
    private javax.swing.JLabel jlP11Card12;
    private javax.swing.JLabel jlP11Card2;
    private javax.swing.JLabel jlP11Card3;
    private javax.swing.JLabel jlP11Card4;
    private javax.swing.JLabel jlP11Card5;
    private javax.swing.JLabel jlP11Card6;
    private javax.swing.JLabel jlP11Card7;
    private javax.swing.JLabel jlP11Card8;
    private javax.swing.JLabel jlP11Card9;
    private javax.swing.JLabel jlP11Name;
    private javax.swing.JLabel jlP1Card1;
    private javax.swing.JLabel jlP1Card10;
    private javax.swing.JLabel jlP1Card11;
    private javax.swing.JLabel jlP1Card12;
    private javax.swing.JLabel jlP1Card2;
    private javax.swing.JLabel jlP1Card3;
    private javax.swing.JLabel jlP1Card4;
    private javax.swing.JLabel jlP1Card5;
    private javax.swing.JLabel jlP1Card6;
    private javax.swing.JLabel jlP1Card7;
    private javax.swing.JLabel jlP1Card8;
    private javax.swing.JLabel jlP1Card9;
    private javax.swing.JLabel jlP1Name;
    private javax.swing.JLabel jlP2Card1;
    private javax.swing.JLabel jlP2Card10;
    private javax.swing.JLabel jlP2Card11;
    private javax.swing.JLabel jlP2Card12;
    private javax.swing.JLabel jlP2Card2;
    private javax.swing.JLabel jlP2Card3;
    private javax.swing.JLabel jlP2Card4;
    private javax.swing.JLabel jlP2Card5;
    private javax.swing.JLabel jlP2Card6;
    private javax.swing.JLabel jlP2Card7;
    private javax.swing.JLabel jlP2Card8;
    private javax.swing.JLabel jlP2Card9;
    private javax.swing.JLabel jlP2Name;
    private javax.swing.JLabel jlP3Card1;
    private javax.swing.JLabel jlP3Card10;
    private javax.swing.JLabel jlP3Card11;
    private javax.swing.JLabel jlP3Card12;
    private javax.swing.JLabel jlP3Card2;
    private javax.swing.JLabel jlP3Card3;
    private javax.swing.JLabel jlP3Card4;
    private javax.swing.JLabel jlP3Card5;
    private javax.swing.JLabel jlP3Card6;
    private javax.swing.JLabel jlP3Card7;
    private javax.swing.JLabel jlP3Card8;
    private javax.swing.JLabel jlP3Card9;
    private javax.swing.JLabel jlP3Name;
    private javax.swing.JLabel jlP4Card1;
    private javax.swing.JLabel jlP4Card10;
    private javax.swing.JLabel jlP4Card11;
    private javax.swing.JLabel jlP4Card12;
    private javax.swing.JLabel jlP4Card2;
    private javax.swing.JLabel jlP4Card3;
    private javax.swing.JLabel jlP4Card4;
    private javax.swing.JLabel jlP4Card5;
    private javax.swing.JLabel jlP4Card6;
    private javax.swing.JLabel jlP4Card7;
    private javax.swing.JLabel jlP4Card8;
    private javax.swing.JLabel jlP4Card9;
    private javax.swing.JLabel jlP4Name;
    private javax.swing.JLabel jlP5Card1;
    private javax.swing.JLabel jlP5Card10;
    private javax.swing.JLabel jlP5Card11;
    private javax.swing.JLabel jlP5Card12;
    private javax.swing.JLabel jlP5Card2;
    private javax.swing.JLabel jlP5Card3;
    private javax.swing.JLabel jlP5Card4;
    private javax.swing.JLabel jlP5Card5;
    private javax.swing.JLabel jlP5Card6;
    private javax.swing.JLabel jlP5Card7;
    private javax.swing.JLabel jlP5Card8;
    private javax.swing.JLabel jlP5Card9;
    private javax.swing.JLabel jlP5Name;
    private javax.swing.JLabel jlP6Card1;
    private javax.swing.JLabel jlP6Card10;
    private javax.swing.JLabel jlP6Card11;
    private javax.swing.JLabel jlP6Card12;
    private javax.swing.JLabel jlP6Card2;
    private javax.swing.JLabel jlP6Card3;
    private javax.swing.JLabel jlP6Card4;
    private javax.swing.JLabel jlP6Card5;
    private javax.swing.JLabel jlP6Card6;
    private javax.swing.JLabel jlP6Card7;
    private javax.swing.JLabel jlP6Card8;
    private javax.swing.JLabel jlP6Card9;
    private javax.swing.JLabel jlP6Name;
    private javax.swing.JLabel jlP7Card1;
    private javax.swing.JLabel jlP7Card10;
    private javax.swing.JLabel jlP7Card11;
    private javax.swing.JLabel jlP7Card12;
    private javax.swing.JLabel jlP7Card2;
    private javax.swing.JLabel jlP7Card3;
    private javax.swing.JLabel jlP7Card4;
    private javax.swing.JLabel jlP7Card5;
    private javax.swing.JLabel jlP7Card6;
    private javax.swing.JLabel jlP7Card7;
    private javax.swing.JLabel jlP7Card8;
    private javax.swing.JLabel jlP7Card9;
    private javax.swing.JLabel jlP7Name;
    private javax.swing.JLabel jlP8Card1;
    private javax.swing.JLabel jlP8Card10;
    private javax.swing.JLabel jlP8Card11;
    private javax.swing.JLabel jlP8Card12;
    private javax.swing.JLabel jlP8Card2;
    private javax.swing.JLabel jlP8Card3;
    private javax.swing.JLabel jlP8Card4;
    private javax.swing.JLabel jlP8Card5;
    private javax.swing.JLabel jlP8Card6;
    private javax.swing.JLabel jlP8Card7;
    private javax.swing.JLabel jlP8Card8;
    private javax.swing.JLabel jlP8Card9;
    private javax.swing.JLabel jlP8Name;
    private javax.swing.JLabel jlP9Card1;
    private javax.swing.JLabel jlP9Card10;
    private javax.swing.JLabel jlP9Card11;
    private javax.swing.JLabel jlP9Card12;
    private javax.swing.JLabel jlP9Card2;
    private javax.swing.JLabel jlP9Card3;
    private javax.swing.JLabel jlP9Card4;
    private javax.swing.JLabel jlP9Card5;
    private javax.swing.JLabel jlP9Card6;
    private javax.swing.JLabel jlP9Card7;
    private javax.swing.JLabel jlP9Card8;
    private javax.swing.JLabel jlP9Card9;
    private javax.swing.JLabel jlP9Name;
    private javax.swing.JPanel jpPlayer0;
    private javax.swing.JPanel jpPlayer1;
    private javax.swing.JPanel jpPlayer10;
    private javax.swing.JPanel jpPlayer11;
    private javax.swing.JPanel jpPlayer2;
    private javax.swing.JPanel jpPlayer3;
    private javax.swing.JPanel jpPlayer4;
    private javax.swing.JPanel jpPlayer5;
    private javax.swing.JPanel jpPlayer6;
    private javax.swing.JPanel jpPlayer7;
    private javax.swing.JPanel jpPlayer8;
    private javax.swing.JPanel jpPlayer9;
    private javax.swing.JPanel jpPlayersEast;
    private javax.swing.JPanel jpPlayersOvest;
    // End of variables declaration//GEN-END:variables

    private void testLoadCard() {
        String curDir = System.getProperty("user.dir");
        String separ = File.separator;
        curDir += separ + "src" + separ + "org" + separ + "smgame" + separ +
                "resource" + separ + "cartemini" +separ + "napoletane" + separ;
        //ImageIcon icon = createImageIcon(curDir + "C01.jpeg");
        ImageIcon icon = new ImageIcon(curDir + "C01.jpg");
        jlP1Card1.setIcon(icon);
        jlP1Card2.setIcon(icon);
        jlP1Card3.setIcon(icon);
        jlP1Card4.setIcon(icon);
        jlP1Card5.setIcon(icon);
        jlP1Card6.setIcon(icon);
        jlP1Card7.setIcon(icon);
        jlP1Card8.setIcon(icon);
        jlP1Card9.setIcon(icon);
        jlP1Card10.setIcon(icon);
        jlP1Card11.setIcon(icon);
        jlP1Card12.setIcon(icon);
        System.out.println(curDir);
        jlP1Card1.setText(null);
        jlP1Card2.setText(null);
        jlP1Card3.setText(null);
        jlP1Card4.setText(null);
        jlP1Card5.setText(null);
        jlP1Card6.setText(null);
        jlP1Card7.setText(null);
        jlP1Card8.setText(null);
        jlP1Card9.setText(null);
        jlP1Card10.setText(null);
        jlP1Card11.setText(null);
        jlP1Card12.setText(null);

        jlP2Card1.setIcon(icon);
        jlP2Card2.setIcon(icon);
        jlP2Card3.setIcon(icon);
        jlP2Card4.setIcon(icon);
        jlP2Card5.setIcon(icon);
        jlP2Card6.setIcon(icon);
        jlP2Card7.setIcon(icon);
        jlP2Card8.setIcon(icon);
        jlP2Card9.setIcon(icon);
        jlP2Card10.setIcon(icon);
        jlP2Card11.setIcon(icon);
        jlP2Card12.setIcon(icon);
        jlP2Card1.setText(null);
        jlP2Card2.setText(null);
        jlP2Card3.setText(null);
        jlP2Card4.setText(null);
        jlP2Card5.setText(null);
        jlP2Card6.setText(null);
        jlP2Card7.setText(null);
        jlP2Card8.setText(null);
        jlP2Card9.setText(null);
        jlP2Card10.setText(null);
        jlP2Card11.setText(null);
        jlP2Card12.setText(null);

        jlP3Card1.setIcon(icon);
        jlP3Card2.setIcon(icon);
        jlP3Card3.setIcon(icon);
        jlP3Card4.setIcon(icon);
        jlP3Card5.setIcon(icon);
        jlP3Card6.setIcon(icon);
        jlP3Card7.setIcon(icon);
        jlP3Card8.setIcon(icon);
        jlP3Card9.setIcon(icon);
        jlP3Card10.setIcon(icon);
        jlP3Card11.setIcon(icon);
        jlP3Card12.setIcon(icon);
        jlP3Card1.setText(null);
        jlP3Card2.setText(null);
        jlP3Card3.setText(null);
        jlP3Card4.setText(null);
        jlP3Card5.setText(null);
        jlP3Card6.setText(null);
        jlP3Card7.setText(null);
        jlP3Card8.setText(null);
        jlP3Card9.setText(null);
        jlP3Card10.setText(null);
        jlP3Card11.setText(null);
        jlP3Card12.setText(null);

        jlP4Card1.setIcon(icon);
        jlP4Card2.setIcon(icon);
        jlP4Card3.setIcon(icon);
        jlP4Card4.setIcon(icon);
        jlP4Card5.setIcon(icon);
        jlP4Card6.setIcon(icon);
        jlP4Card7.setIcon(icon);
        jlP4Card8.setIcon(icon);
        jlP4Card9.setIcon(icon);
        jlP4Card10.setIcon(icon);
        jlP4Card11.setIcon(icon);
        jlP4Card12.setIcon(icon);
        jlP4Card1.setText(null);
        jlP4Card2.setText(null);
        jlP4Card3.setText(null);
        jlP4Card4.setText(null);
        jlP4Card5.setText(null);
        jlP4Card6.setText(null);
        jlP4Card7.setText(null);
        jlP4Card8.setText(null);
        jlP4Card9.setText(null);
        jlP4Card10.setText(null);
        jlP4Card11.setText(null);
        jlP4Card12.setText(null);

        jlP5Card1.setIcon(icon);
        jlP5Card2.setIcon(icon);
        jlP5Card3.setIcon(icon);
        jlP5Card4.setIcon(icon);
        jlP5Card5.setIcon(icon);
        jlP5Card6.setIcon(icon);
        jlP5Card7.setIcon(icon);
        jlP5Card8.setIcon(icon);
        jlP5Card9.setIcon(icon);
        jlP5Card10.setIcon(icon);
        jlP5Card11.setIcon(icon);
        jlP5Card12.setIcon(icon);
        jlP5Card1.setText(null);
        jlP5Card2.setText(null);
        jlP5Card3.setText(null);
        jlP5Card4.setText(null);
        jlP5Card5.setText(null);
        jlP5Card6.setText(null);
        jlP5Card7.setText(null);
        jlP5Card8.setText(null);
        jlP5Card9.setText(null);
        jlP5Card10.setText(null);
        jlP5Card11.setText(null);
        jlP5Card12.setText(null);

        jlP6Card1.setIcon(icon);
        jlP6Card2.setIcon(icon);
        jlP6Card3.setIcon(icon);
        jlP6Card4.setIcon(icon);
        jlP6Card5.setIcon(icon);
        jlP6Card6.setIcon(icon);
        jlP6Card7.setIcon(icon);
        jlP6Card8.setIcon(icon);
        jlP6Card9.setIcon(icon);
        jlP6Card10.setIcon(icon);
        jlP6Card11.setIcon(icon);
        jlP6Card12.setIcon(icon);
        jlP6Card1.setText(null);
        jlP6Card2.setText(null);
        jlP6Card3.setText(null);
        jlP6Card4.setText(null);
        jlP6Card5.setText(null);
        jlP6Card6.setText(null);
        jlP6Card7.setText(null);
        jlP6Card8.setText(null);
        jlP6Card9.setText(null);
        jlP6Card10.setText(null);
        jlP6Card11.setText(null);
        jlP6Card12.setText(null);

        jlP7Card1.setIcon(icon);
        jlP7Card2.setIcon(icon);
        jlP7Card3.setIcon(icon);
        jlP7Card4.setIcon(icon);
        jlP7Card5.setIcon(icon);
        jlP7Card6.setIcon(icon);
        jlP7Card7.setIcon(icon);
        jlP7Card8.setIcon(icon);
        jlP7Card9.setIcon(icon);
        jlP7Card10.setIcon(icon);
        jlP7Card11.setIcon(icon);
        jlP7Card12.setIcon(icon);
        jlP7Card1.setText(null);
        jlP7Card2.setText(null);
        jlP7Card3.setText(null);
        jlP7Card4.setText(null);
        jlP7Card5.setText(null);
        jlP7Card6.setText(null);
        jlP7Card7.setText(null);
        jlP7Card8.setText(null);
        jlP7Card9.setText(null);
        jlP7Card10.setText(null);
        jlP7Card11.setText(null);
        jlP7Card12.setText(null);

        jlP8Card1.setIcon(icon);
        jlP8Card2.setIcon(icon);
        jlP8Card3.setIcon(icon);
        jlP8Card4.setIcon(icon);
        jlP8Card5.setIcon(icon);
        jlP8Card6.setIcon(icon);
        jlP8Card7.setIcon(icon);
        jlP8Card8.setIcon(icon);
        jlP8Card9.setIcon(icon);
        jlP8Card10.setIcon(icon);
        jlP8Card11.setIcon(icon);
        jlP8Card12.setIcon(icon);
        jlP8Card1.setText(null);
        jlP8Card2.setText(null);
        jlP8Card3.setText(null);
        jlP8Card4.setText(null);
        jlP8Card5.setText(null);
        jlP8Card6.setText(null);
        jlP8Card7.setText(null);
        jlP8Card8.setText(null);
        jlP8Card9.setText(null);
        jlP8Card10.setText(null);
        jlP8Card11.setText(null);
        jlP8Card12.setText(null);

    }


}
