package org.smgame.frontend;

import org.smgame.frontend.NewJFrame1;
import org.smgame.frontend.FormattedTextField;
import java.awt.Dimension;
import java.io.File;
import javax.swing.ImageIcon;

public class NewJFrame1 extends javax.swing.JFrame {

    public NewJFrame1() {
        this.setPreferredSize(new Dimension(1024, 768));
        initComponents();        
        add(new FormattedTextField());
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void testLoadCard() {
        String curDir = System.getProperty("user.dir");
        String separ = File.separator;
        curDir += separ + "src" + separ + "org" + separ + "smgame" + separ +
                "resource" + separ + "cartemini" + separ + "napoletane" + separ;
        ImageIcon icon = new ImageIcon(curDir + "C01.jpg");

        
    }
}
